obj-y := kdfsan_custom.o kdfsan_init.o kdfsan_interface.o kdfsan_internal.o kdfsan_mm.o kdfsan_shadow.o kdfsan_policies.o kdfsan_util.o

KASAN_SANITIZE := n
KDFSAN_SANITIZE := n
KCOV_INSTRUMENT := n
UBSAN_SANITIZE := n
