# SPDX-License-Identifier: GPL-2.0

obj-y := kdfsan_custom.o kdfsan_init.o kdfsan_interface.o kdfsan_internal.o kdfsan_mm.o kdfsan_shadow.o kdfinit_taint.o

KASAN_SANITIZE := n
KDFSAN_SANITIZE := n
KCOV_INSTRUMENT := n
UBSAN_SANITIZE := n
